### ISSUE TITLE
Error in prov.visualize() when folder name contains space

### ISSUE THREAD

**Issue by ngohoanglankhanh** [End-to-end-provenance/provViz#36]
[
![Screen Shot 2019-05-31 at 1 58 15 PM](https://user-images.githubusercontent.com/34677238/58807821-ce340a00-85e6-11e9-9610-0a3f9323db0b.png)
](url)

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/provViz/commit/5b49613348f137eb84b515672dd8aa93ef1ca340
